// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpError-0]
	_ = x[OpConnCreate-1]
	_ = x[OpConnAccept-2]
	_ = x[OpConnClose-3]
	_ = x[OpConnCopy-4]
}

const _OpCode_name = "OpErrorOpConnCreateOpConnAcceptOpConnCloseOpConnCopy"

var _OpCode_index = [...]uint8{0, 7, 19, 31, 42, 52}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
