// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpError-0]
	_ = x[OpConnCreate-1]
	_ = x[OpConnAccept-2]
	_ = x[OpConnClose-3]
	_ = x[OpConnCopy-4]
	_ = x[OpProtoNegotiate-5]
	_ = x[OpProtoAck-6]
	_ = x[OpStandardLinkCopy-255]
}

const (
	_OpCode_name_0 = "OpErrorOpConnCreateOpConnAcceptOpConnCloseOpConnCopyOpProtoNegotiateOpProtoAck"
	_OpCode_name_1 = "OpStandardLinkCopy"
)

var (
	_OpCode_index_0 = [...]uint8{0, 7, 19, 31, 42, 52, 68, 78}
)

func (i OpCode) String() string {
	switch {
	case i <= 6:
		return _OpCode_name_0[_OpCode_index_0[i]:_OpCode_index_0[i+1]]
	case i == 255:
		return _OpCode_name_1
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
